### ISSUE TITLE
Minor Aircraft Movements while switching scenes

### ISSUE THREAD

**Issue by AdamJCavanaugh** [jamesg31/TowerGame#20]
When switching between asdex and radar scenes (using Ecs), the aircraft appear to be slightly "lower" in radar view than asdex.

**Comment by jamesg31** [comment]
Just realized the reasoning for this, the coods for the runway where kinda just estimated using skyvector. This is just happening because the asdex uses the actual and fairly precise runway coordinates, but the runway doesnt. It isnt a problem with the aircraft position, but just the runway location. I never got around to fixing it!
